### ISSUE TITLE
Posts infringing community rules should be closed, not deleted

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-api#221] opened 2019-03-24 10:34 UTC
Posts which are removed due to community rules such as off-topic should not be removed, but "closed". Meaning only admins/moderators/poster can comment on it and it's hidden from the feeds. 

The operation should also be reversible.

This gives a place for moderators/admins/posters to discuss the reasons why the post was closed down, and the ability of the poster not loosing its content.

This should also trigger a notification to the poster to let him know that it has been closed.

Perhaps a way for moderators to state the why is also desirable.

**Comment by uiboy** [comment] 2019-05-03 11:45
Duplicate of #376 (already released)

**Closed by uiboy** 2019-05-03 11:45 UTC
Labels: communities, feature, moderation, priority:high
